### ISSUE TITLE
TB Issue #6 - Пропадает возможность управлять танком

### ISSUE THREAD

**Issue by GSilidis** [Lonsofore/TankBattles#10]
Если кликнуть в любой точке поля, кроме танка игрока, то игрок теряет управление танком пока снова не нажмет на свой танк.

**Comment by Lonsofore** [comment]
Да, точно. Тоже замечал такое. Запретить игроку кликать? :D

**Comment by GSilidis** [comment]
Думаю нужно просто не давать менять фокус. Или при изменении фокуса переключать обратно на танк.

**Comment by Lonsofore** [comment]
Тоже вариант

**Comment by Lonsofore** [comment]
Исправлено
